### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Hallowizer/thaumcraft-7#1]
Hey,

Attempted to build this just to see what it was like in game but just game back pumping out errors.

![image](https://user-images.githubusercontent.com/20475516/60830402-0662d580-a1af-11e9-831a-81487ba58fd8.png)

**Comment by Hallowizer** [comment]
You have to add lombok to the compiler's classpath to make this work, I haven't added it to the gradle file.
